# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Zoom.ZoomClientforMeetings
PackageVersion: 5.16.26186
PackageLocale: en-US
Publisher: Zoom
PackageName: Zoom Client for Meetings (All Users 64-bit)
License: Proprietary
ShortDescription: Zoom's secure, reliable video platform powers all of your communication needs, including meetings, chat, phone, webinars, and online events. (All Users Installer 64-bit)
ManifestType: defaultLocale
ManifestVersion: 1.5.0
